title: "/co"
name: "barra co"
keywords: "hacker, hacker culture, hackerspace, hackerspaces"
url: "https://barraco.github.io/"
description: "O /co é um <a href=\"http://hackerspaces.org\">hackerspace</a> dedicado a compartilhar conhecimento de forma livre e colaborativa."

lang: "pt-BR"
copyrightYear: "2018"